name = "vps-subscription-panel"
main = "src/index.ts"
compatibility_date = "2026-06-14"

rules = [
  { type = "Text", globs = ["**/*.yaml"], fallthrough = true }
]

[[d1_databases]]
binding = "DB"
database_name = "vps_subscription_db"
database_id = "00ec4f0c-6405-4eb0-ae6a-63ea0f7b122c"
